app = "kotcoder"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "lax"
processes = []

[env]
CODER_ACCESS_URL = "https://coder.yukata.tech"
CODER_OAUTH2_GITHUB_ALLOWED_ORGS = "yukata-tech,readifcute"
CODER_OAUTH2_GITHUB_ALLOW_SIGNUPS = "true"
CODER_WILDCARD_ACCESS_URL = "*.coder.yukata.tech"
SWAP = "true"

[experimental]
allowed_public_ports = []
auto_rollback = true

[[services]]
http_checks = []
internal_port = 8080
processes = ["app"]
protocol = "tcp"
script_checks = []

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 0
timeout = "2s"
